spring.application.name=bookstore-api
server.port=8080
server.servlet.context-path=/Project

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QLBanSach;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=false

spring.mvc.hiddenmethod.filter.enabled=true

# Exclude Spring Boot JPA auto-config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
